### ISSUE TITLE
Allow moment().from() syntax

### ISSUE THREAD

**Issue by blanchg** [researchgate/moment-shortformat#13]
Hi,
I need to be able to customize the "now" being used in .short().
More than happy to add this and submit a pull request if you would like.
What is your preference for the implementation, a new parameter to the existing .short() method or a new method?

e.g. 
moment().short(false, now)

Moment itself uses two methods .fromNow() and .from(now) but that would mean a breaking change to your api which probably isn't really necessary.

Thanks!

**Comment by danez** [comment]
That is a nice suggestion. Having it close to the moment.js APIs would be nice, but `.shortNow()` is not a really speaking name and it would completely be a new API if we change this.
So I'm fine with doing `moment().short(false, now)`.

**Comment by blanchg** [comment]
Ok I will create a pull request shortly or if you want to add it I don't mind.

    shortFormat = function(withoutPreOrSuffix, now) {
      var diff, num, result, unit;
      now = now || moment();

    ...

    moment.fn.short = function(withoutPreOrSuffix, now) {
      return shortFormat.call(this, withoutPreOrSuffix, now);
    };
